resources:
#  Resources specifies builds, repositories, pipelines, and other resources that will be used by the pipeline.
#  Here in our example we are specifying the repository being used i.e cnap-templates-pipeline-azure.
#  Also name or the tag which should be used is specified under ref
  repositories:
    - repository: cnap-templates-pipeline-azure
      type: git
      name: cnap-templates-pipeline-azure
      ref: refs/tags/v0.77
#Defining the variables that will be used in pipeline. Here we are specifying the image, and it's name.
variables:
  image: exercise3-oracle-service
  name: exercise3-oracle-service

#Stages are nothing but a collection of related jobs. In our example we are passing template cnap-templates-pipeline-azure
#which will run steps involved in azure-stage-build-and-deploy.yml. parameters are the values used by stage template.
stages:
  - template: azure-stage-build-and-deploy.yml@cnap-templates-pipeline-azure
    parameters:
      image: $(image)
      name: $(name)
